//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "請填寫客戶名稱")]
        [StringLength(10, ErrorMessage = "測試中，本系統名稱最長允許10個字元")]
        public string 客戶名稱 { get; set; }
        [Required(ErrorMessage = "請填寫統一編號")]
        [RegularExpression(@"^[0-9]{8}$", ErrorMessage = "測試中，統一編號應為八碼數字")]
        public string 統一編號 { get; set; }
        [Required(ErrorMessage = "請填寫電話號碼")]
        //[RegularExpression(@"^09\d{2}-?\d{3}-?\d{3}$", ErrorMessage = "測試中，電話號碼應為0975-111-111等正確格式")]
        [RegularExpression(@"^09\d{2}-?\d{6}$", ErrorMessage = "測試中，電話號碼應為0975-111111等正確格式")]
        public string 電話 { get; set; }
        [Required(ErrorMessage = "請填寫傳真號碼")]
        [RegularExpression(@"^0\d{1}-?\d{8}$", ErrorMessage = "測試中，傳真號碼應為02-23517988")]
        public string 傳真 { get; set; }
        [Required(ErrorMessage = "請填寫地址")]
        [StringLength(30, ErrorMessage = "測試中，本系統最長允許30個字元")]
        public string 地址 { get; set; }
        [Required(ErrorMessage = "請填寫Email")]
        [EmailAddressAttribute(ErrorMessage = "測試中，Email格式應符合sales.24drs@24drs.com等正確格式")]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}
